#
# A Generic Tabu Search Solver
#
import os
import abc
import time
import json
from munch import Munch

# import pprint


class TabuSearchProblem(object):
    def __init__(self):
        self._requests = {}

    @abc.abstractmethod
    def initial_solution(self):
        #
        # Generate initial solution
        # Returns: the solution
        #
        pass  # pragma: no cover

    @abc.abstractmethod
    def moves(self, solution, value):
        #
        # Returns a generator that iteratively yields tuples with values:
        # (neighbor, move used to generate the neighbor, value of the neighbor (or None))
        #
        pass  # pragma: no cover

    @abc.abstractmethod
    def compute_results(self, solution):
        #
        # Compute the value of a solution and other results
        # Returns tuple: (float value for the solution, other results data)
        #
        pass  # pragma: no cover

    def request_results(self, solution):
        #
        # Submit a request to compute results for a solution
        # Returns: None
        #
        self._requests[solution] = 1

    def cancel_request(self, solution):
        #
        # Cancel a request to compute results for a solution
        # Returns: None
        #
        if solution in self._requests:
            del self._requests[solution]

    def cancel_all_requests(self):
        #
        # Cancel all requests to compute results for solutions
        # Returns: None
        #
        self._requests = {}

    def get_requested_results(self):
        #
        # Get results associated with a solution requested earlier
        # Returns: tuple containing the solution, the solution value, and other results
        #
        if len(self._requests) == 0:
            return None
        solution = self._requests.popitem()[0]
        value, results = self.compute_results(solution)
        return solution, value, results

    def write_solution_to_file(self, iteration, point, value, filename):
        #
        # Write information about the current point to the specified file.
        #
        tmp = {"iteration": iteration, "value": value, "point": point}
        with open(filename, "w") as OUTPUT:
            OUTPUT.write(json.dumps(tmp))


class TabuSearch(object):
    def __init__(self, problem=None):
        self.options = Munch()
        #
        # If greater than zero, then this specifies the maximum number of
        # iterations that Tabu Search is executed
        #
        self.options.max_iterations = 100
        #
        # If greater than zero, then this specifies the maximum number of
        # iterations that Tabu Search is allowed to continue without finding
        # an improving solution.
        #
        self.options.max_stall_count = self.options.max_iterations / 4
        self.options.tabu_tenure = 2
        #
        # Search strategies
        #   first_improving - Consider each move generated by the problem object, and
        #                       accept the first improving solution
        #   best_improving - Consider all moves generated by the problem object, and
        #                       accept the best improving solution
        #   async_first_improving - Consider all moves generated by the problem object, and
        #                       asyncronously accept the first improving solution
        #
        self.options.search_strategy = "first_improving"
        self.options.verbose = False
        self.options.debug = False
        #
        # If specified, then the iteration count is used to fill in this
        # file name template.
        #
        self.options.checkpoint_file_template = None
        #
        self.iteration = 0
        self.stall_count = 0
        #
        self.search_strategies = {
            "first_improving": self.search_neighborhood_first_improving,
            "best_improving": self.search_neighborhood_best_improving,
            "async_first_improving": self.search_neighborhood_async_first_improving,
        }
        #
        # Mapping from solution to iteration count.  A move is ignored (i.e. it is
        # tabu), if (tabu_time[move] >= self.iteration) is true ... unless it
        # has a better value than the best point seen so far.
        #
        self.tabu_time = {}
        #
        # An object that defines problem-specific operations, including
        # generating an initial solution, generating moves and computing
        # solution values.
        #
        self.problem = problem

    def initial_solution(self):
        #
        # Generate initial solution
        # Returns: the solution
        #
        return self.problem.initial_solution()

    def moves(self, solution, value):
        #
        # Returns a generator that iteratively yields tuples with values:
        # (neighbor, move used to generate the neighbor, value of the neighbor (or None))
        #
        return self.problem.moves(solution, value)

    def evaluate(self, solution):
        #
        # Compute the results for a solution, and return the value
        #
        return self.problem.compute_results(solution)[0]

    def request_results(self, solution):
        #
        # Submit a request to compute results for a solution
        # Returns: None
        #
        self.problem.request_results(solution)

    def cancel_request(self, solution):
        #
        # Cancel a request to compute results for a solution
        # Returns: None
        #
        self.problem.cancel_request(solution)

    def cancel_all_requests(self):
        #
        # Cancel all requests to compute results for solutions
        # Returns: None
        #
        self.problem.cancel_all_requests()

    def get_requested_results(self):
        #
        # Get results associated with a solution requested earlier
        # Returns: tuple containing the solution, the solution value, and other results
        #
        return self.problem.get_requested_results()

    def write_solution_to_file(self, iteration, point, value, filename):
        #
        # Write information about the current point to the specified file.
        #
        self.problem.write_solution_to_file(iteration, point, value, filename)

    def search_neighborhood(self, x, f_x, f_best):
        #
        # Generate moves in the neighborhood to find the best point. Evaluate them
        # if their value is not already known.
        #
        # The default behavior of the TabuSearch class is to use a first-improving
        # search strategy, but the best-improving strategy can also be used.
        #
        return self.search_strategies[self.options.search_strategy](x, f_x, f_best)

    def search_neighborhood_first_improving(self, x, f_x, f_best):
        #
        # This executes search in a greedy manner, updating
        # the current iterate, x_, as soon as a neighbor with an improving value
        # is found.
        #
        move_ = None
        x_ = None
        f_ = float("inf")
        tabu = False

        for neighbor, move, value in self.moves(x, f_x):
            if value is None:
                value = self.evaluate(neighbor)
            if move in self.tabu_time and self.tabu_time[move] >= self.iteration:
                if self.options.verbose:  # pragma: no cover
                    print(
                        "#   TABU Move: {}  TABU Time: {}".format(
                            move, self.tabu_time[move]
                        )
                    )
                # Aspiration criteria: Always keep best point found so far
                if value < f_best:
                    f_best = value
                    move_, x_, f_ = move, neighbor, value
                    tabu = True
                    break
            elif value < f_x:
                move_, x_, f_ = move, neighbor, value
                break
            elif value < f_:
                move_, x_, f_ = move, neighbor, value

        if move_ is not None:
            self.tabu_time[move_] = self.iteration + self.options.tabu_tenure
            if self.options.verbose:  # pragma: no cover
                print(
                    "#   TABU UPDATE  X: {}  Move: {}  TABU Time: {}".format(
                        x_, move, self.tabu_time[move_]
                    )
                )

        return x_, f_, tabu

    def search_neighborhood_best_improving(self, x, f_x, f_best):
        """
        Search for all improving neighbors, and keeps the best one.
        """
        #
        # Queue all evaluations and collect them.  This allows for parallel
        # evaluation of neighbors.
        #
        _evaluated = {}
        _queued = {}
        for neighbor, move, value in self.moves(x, f_x):
            if value is not None:
                _evaluated[neighbor] = move, value
            else:
                _queued[neighbor] = move
                self.request_results(neighbor)
                if self.options.debug:
                    print("Requested evaluation - Point {}".format(neighbor))
        #
        # Collect evaluated neighbors
        #
        curr = 0
        while len(_queued) > 0:
            if self.options.debug or self.options.verbose:
                if curr % 10 == 0:
                    print("Waiting for {} queued evaluations".format(len(_queued)))
                curr += 1
            #
            # Collect evaluated neighbors until there are no more
            #
            solution_results = self.get_requested_results()
            while solution_results is not None:
                neighbor, value, results = solution_results
                if self.options.debug:
                    print(
                        "Received Results - Point {}  Value {}".format(neighbor, value)
                    )
                    print("Queued: {}".format(list(sorted(_queued.keys()))))
                _evaluated[neighbor] = _queued[neighbor], value  # move, value
                del _queued[neighbor]
                if self.options.debug:
                    print(
                        "Evaluation Complete - Point {}  Value {}".format(
                            neighbor, value
                        )
                    )
                solution_results = self.get_requested_results()
            #
            # Sleep if we've collected all available evaluations and need to
            # wait for more
            #
            if len(_queued) > 0:  # pragma: no cover
                time.sleep(0.1)
        #
        # Process the list of evaluated neighbors
        #
        # NOTE: Reverse sorting the examination of the neighbor list here creates a bias.  When multiple
        # solutions have the same value, the one that is generated "last" is selected.  This helps
        # encourage diversity of solutions being searched.
        #
        move_ = None
        x_ = None
        f_ = float("inf")
        tabu = False
        for neighbor in sorted(_evaluated.keys(), reverse=True):
            move, value = _evaluated[neighbor]
            if move in self.tabu_time and self.tabu_time[move] >= self.iteration:
                if self.options.verbose:
                    print(
                        "#   TABU Move: {}  TABU Time: {}".format(
                            move, self.tabu_time[move]
                        )
                    )
                # Aspiration criteria: Always keep best point found so far
                if value < f_best:
                    f_best = value
                    move_, x_, f_ = move, neighbor, value
                    tabu = True
            elif value < f_x:
                move_, x_, f_ = move, neighbor, value
                tabu = False
            elif value < f_:
                move_, x_, f_ = move, neighbor, value
                tabu = False
        #
        # Update the tabu time for the best move, and return
        #
        if move_ is not None:
            self.tabu_time[move_] = self.iteration + self.options.tabu_tenure
        return x_, f_, tabu

    def search_neighborhood_async_first_improving(self, x, f_x, f_best):
        """
        Queue search for all improving neighbors, and keep first improving one.
        """
        #
        # Queue all evaluations and collect them.  This allows for parallel
        # evaluation of neighbors.
        #
        _evaluated = {}
        _queued = {}
        for neighbor, move, value in self.moves(x, f_x):
            if value is not None:
                _evaluated[neighbor] = move, value
            else:
                _queued[neighbor] = move
                self.request_results(neighbor)
                if self.options.debug:
                    print("Requested evaluation - Point {}".format(neighbor))

        def next_point():
            #
            # Consider new points first, since this increases the
            # diversity of points considered by TS
            #
            while len(_queued) > 0:
                solution_results = self.get_requested_results()
                if solution_results is None:
                    continue
                neighbor, value, results = solution_results
                if neighbor in _queued:
                    move = _queued[neighbor]
                    yield neighbor, move, value
                    del _queued[neighbor]
                else:
                    #
                    # If this is a solution generated in a previous iteration of
                    # of the search algorithm, then we don't know its move.
                    #
                    yield neighbor, None, value
            for neighbor in _evaluated:
                move, value = _evaluated[neighbor]
                yield neighbor, move, value

        #
        # This executes search in a greedy manner, updating
        # the current iterate, x_, as soon as a neighbor with an improving value
        # is found.
        #
        move_ = None
        x_ = None
        f_ = float("inf")
        tabu = False

        for neighbor, move, value in next_point():
            assert value is not None
            if move in self.tabu_time and self.tabu_time[move] >= self.iteration:
                if self.options.verbose:  # pragma: no cover
                    print(
                        "#   TABU Move: {}  TABU Time: {}".format(
                            move, self.tabu_time[move]
                        )
                    )
                # Aspiration criteria: Always keep best point found so far
                if value < f_best:
                    f_best = value
                    move_, x_, f_ = move, neighbor, value
                    tabu = True
                    break
            elif value < f_x:
                move_, x_, f_ = move, neighbor, value
                break
            elif value < f_:
                move_, x_, f_ = move, neighbor, value

        if move_ is not None:
            self.tabu_time[move_] = self.iteration + self.options.tabu_tenure
            if self.options.verbose:  # pragma: no cover
                print(
                    "#   TABU UPDATE  X: {}  Move: {}  TABU Time: {}".format(
                        x_, move, self.tabu_time[move_]
                    )
                )

        self.cancel_all_requests()
        return x_, f_, tabu

    def end_iteration(self):
        # End-of-iteration operations
        pass

    def run(self):
        x_best = x = self.initial_solution()
        f_best = f_x = self.evaluate(x)

        self.stall_count = 0
        while True:
            #
            # Find the best neighbor
            #
            x_nbhd, f_nbhd, tabu = self.search_neighborhood(x, f_x, f_best)
            #
            # Update the best point seen so far
            #
            if f_nbhd < f_best:
                #
                # Found a point that improved on the globally best
                #
                x_best, f_best = x_nbhd, f_nbhd
                x, f_x = x_nbhd, f_nbhd
                self.stall_count = 0
                #
                # Write file with improving solution
                #
                if self.options.checkpoint_file_template:
                    self.write_solution_to_file(
                        self.iteration,
                        x_best,
                        f_best,
                        self.options.checkpoint_file_template.format(self.iteration),
                    )
            else:
                #
                # Update the current point to the point generated
                # in our search of the neighborhood
                #
                if x_nbhd is not None:
                    x, f_x = x_nbhd, f_nbhd
                self.stall_count += 1
            #
            # End iteration
            #
            self.end_iteration()
            self.iteration += 1
            if self.options.verbose:  # pragma: no cover
                print(
                    "\n# Iteration: {}\n# Best objective: {}\n# Current Objective: {}\n# Current Point: {}\n".format(
                        self.iteration, f_best, f_x, x
                    )
                )
            else:
                print(
                    "# Iteration: {}  Best objective: {}  Current Objective: {}".format(
                        self.iteration, f_best, f_x
                    )
                )
            #
            # Check termination
            #
            if self.iteration >= self.options.max_iterations:  # pragma: no cover
                print("# Termination at iteration {}".format(self.iteration))
                break
            if self.stall_count >= self.options.max_stall_count:  # pragma: no cover
                print(
                    "# Termination after {} stalled iterations.".format(
                        self.stall_count
                    )
                )
                break

        self.cancel_all_requests()
        self.finalize_run(x_best, f_best)
        return x_best, f_best

    def finalize_run(self, x_best, f_best):
        print("# Final Results")
        print("#   Best Value: {}".format(f_best))
        print("#   Best Solution: {}".format(x_best))

        if self.options.debug:  # pragma: no cover
            print("\nFinal TABU Table")
            if len(self.tabu_time) > 0:
                for move in sorted(self.tabu_time.keys()):
                    print(move, self.tabu_time[move])
            else:
                print("\n  None")


class CachedTabuSearch(TabuSearch):
    """
    Avoid re-evaluating points that are have been previously evaluated.  All values are cached.
    """

    def __init__(self, problem=None):
        TabuSearch.__init__(self, problem=problem)
        self.cache = {}
        self.results_ = {}
        self.num_moves_evaluated = 0

    def moves(self, solution, value):
        for n, m, v in self.problem.moves(solution, value):
            self.num_moves_evaluated += 1
            if v is None:
                v = self.cache.get(n, None)
                if v is not None and self.options.verbose:  # pragma: no cover
                    print("CACHED MOVE:     {}  VALUE: {}".format(n, v))
            yield (n, m, v)

    def evaluate(self, solution):
        value = self.cache.get(solution, None)
        if value is not None:
            if self.options.verbose:  # pragma: no cover
                print("CACHED SOLUTION: {}  VALUE: {}".format(solution, value))
            return value

        value, results = self.problem.compute_results(solution)
        self.cache[solution] = value
        self.results_[solution] = results
        # print("HERE - CACHING",solution,value)
        if self.options.verbose:  # pragma: no cover
            print("EVALUATED:       {}  VALUE: {}".format(solution, value))
        # pprint.pprint(self.cache)
        return value

    def get_requested_results(self):
        solution_results = self.problem.get_requested_results()
        if solution_results is not None:
            solution, value, results = solution_results
            self.cache[solution] = value
            self.results_[solution] = results
            if self.options.verbose:  # pragma: no cover
                print("REQUEST EVALUATED: {}  VALUE: {}".format(solution, value))
        return solution_results

    def finalize_run(self, x_best, f_best):
        print("# Final Results")
        print("#   Best Value: {}".format(f_best))
        print("#   Best Solution: {}".format(x_best))
        print("#   Num Unique Solutions Evaluated: {}".format(len(self.cache)))
        print("#   Num Solutions Evaluated: {}".format(self.num_moves_evaluated))

        if self.options.debug:  # pragma: no cover
            print("\nFinal TABU Table")
            if len(self.tabu_time) > 0:
                for move in sorted(self.tabu_time.keys()):
                    print(move, self.tabu_time[move])
            else:
                print("\n  None")

    @property
    def results(self):
        #
        # Return the cached results
        #
        return self.results_
