#!/bin/sh

for fname in `ls *results.yaml`; do
    nname=`echo $fname | sed 's#\(.*\)_results\.yaml#\1_baseline.yaml#'`
    echo $nname
    mv $fname $nname
done || true

for fname in `ls *results.csv`; do
    nname=`echo $fname | sed 's#\(.*\)_results\.csv#\1_baseline.csv#'`
    echo $nname
    mv $fname $nname
done || true
